### ISSUE TITLE
Why the values of some specific activations are forced to reset?

### ISSUE THREAD

**Issue by Jakexxh** [ThomasMiconi/BiologicallyPlausibleLearningRNN#1]
After computing network activations, in your code,  ` x(1)=1.0; x(10)=1.0;x(11)=-1.0; //x(12) = 1.0;  // Biases`,  three specific activations is forced to set as constants. Can you explain why?

**Comment by ThomasMiconi** [comment]
These play the roles of biases in the network, through their output connections to all other neurons. 

Without those, in the absence of input or perturbations, all neurons would have output 0. These biases allow neurons to have a non-zero resting firing rate, as real neurons do.

**Comment by Jakexxh** [comment]
Understand! Thanks for your reply.
